#!/usr/bin/env python
import argparse
import MySQLdb
import settings
from storagemanager import StorageManager
from storagemanager import SnapshotSchedule

dbconn = MySQLdb.connect(host=settings.TRACKING_DB['host'],
                     port=settings.TRACKING_DB['port'],
                     user=settings.TRACKING_DB['user'],
                     passwd=settings.TRACKING_DB['pass'],
                     db=settings.TRACKING_DB['dbname'])
db = dbconn.cursor()

human_output = True
sm = StorageManager()



def host_list(args):
    whereclauses = []
    if args.search_field:
        if args.like:
            whereclauses.append("{0} like '%{1}%'".format(args.search_field, args.like))
        elif args.prefix:
            whereclauses.append("{0} like '%{1}%'".format(args.search_field, args.prefix))
    if args.zone:
        whereclauses.append("availability_zone like '{0}%'".format(args.zone))

    sql = "select host, instance_id, availability_zone from hosts"
    if len(whereclauses):
        sql += " where " + " and ".join(whereclauses)
    db.execute(sql)
    results = db.fetchall()

    if human_output:
        print "Hosts found:\n"
        print "Hostname\tinstance_id\tavailability_zone"
        print "--------------------------------------------------------------"
    for res in results:
        print "{0}\t{1}\t{2}".format(res[0], res[1], res[2])
    if human_output:
        print "--------------------------------------------------------------"


def volume_list(args):
    whereclauses = []
    if args.search_field:
        if args.search_field in ('host', 'instance_id'):
            args.search_field = "h." + args.search_field
        if args.like:
            whereclauses.append("{0} like '%{1}%'".format(args.search_field, args.like))
        elif args.prefix:
            whereclauses.append("{0} like '%{1}%'".format(args.search_field, args.prefix))
    if args.zone:
        whereclauses.append("h.availability_zone like '{0}%'".format(args.zone))

    sql = "select " \
            "host, " \
            "h.instance_id, " \
            "h.availability_zone, " \
            "vg.volume_group_id, " \
            "count(*) as volumes_in_group, " \
            "raid_level, " \
            "sum(size) as GiB, " \
            "piops " \
            "from " \
            "hosts h " \
            "left join host_volumes hv on h.instance_id=hv.instance_id " \
            "left join volume_groups vg on vg.volume_group_id=hv.volume_group_id " \
            "left join volumes v on v.volume_group_id=vg.volume_group_id"

    if len(whereclauses):
        sql += " where " + " and ".join(whereclauses)
    sql += " group by vg.volume_group_id"
    db.execute(sql)
    results = db.fetchall()

    if human_output:
        print "Volumes found:\n"
        print "Hostname\tinstance_id\tavailability_zone\tvolume_group_id\tvolumes_in_group\traid_level\tGiB\tiops"
        print "--------------------------------------------------------------"
    for res in results:
        print "{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}".format(res[0],res[1],res[2],res[3],res[4],res[5],res[6],res[7])
    if human_output:
        print "--------------------------------------------------------------"


def volume_create(args):
    print "volume create function"

def volume_attach(args):
    print "volume attach function"

def snapshot_create_volume(args):
    sm.snapshot_volume_group(args.volume_group_id, args.description, args.pre, args.post)


def snapshot_create_host(args):
    whereclauses = []
    if args.instance:
        whereclauses.append("h.instance_id = '{}'".format(args.instance))
    elif args.host:
        whereclauses.append("h.host = '{}'".format(args.host))

    if args.mount_point:
        whereclauses.append("hv.mount_point = '{}'".format(args.mount_point))

    sql = "select " \
          "hv.volume_group_id " \
          "from " \
          "hosts h " \
          "left join host_volumes hv on h.instance_id=hv.instance_id "
    sql += " where " + " and ".join(whereclauses)
    db.execute(sql)
    res = db.fetchone()
    if res:
        sm.snapshot_volume_group(res[0], args.description, args.pre, args.post)
    else:
        print "Volume group not found"
        exit(1)

def snapshot_schedule_list(args):
    whereclauses = []
    order_by = ''
    if args.resource == 'host':
        if args.resource_id:
            whereclauses.append("hostname = '{}'".format(args.resource_id))
        elif args.prefix:
            whereclauses.append("hostname like '{}%'".format(args.prefix))
        elif args.like:
            whereclauses.append("hostname like '%{}%'".format(args.like))
        order_by = " order by hostname asc"
    elif args.resource == 'instance':
        if args.resource_id:
            whereclauses.append("instance_id = '{}'".format(args.resource_id))
        elif args.prefix:
            whereclauses.append("instance_id like '{}%'".format(args.prefix))
        elif args.like:
            whereclauses.append("instance_id like '%{}%'".format(args.like))
        order_by = " order by instance_id asc"
    elif args.resource == 'volume':
        if args.resource_id:
            whereclauses.append("volume_group_id = {}".format(args.resource_id))

    sql = "select " \
          "schedule_id," \
          "hostname," \
          "instance_id," \
          "mount_point," \
          "volume_group_id," \
          "concat(interval_hour,'-',interval_day,'-',interval_week,'-',interval_month)," \
          "concat(retain_hourly,'-',retain_daily,'-',retain_weekly,'-',retain_monthly,'-',retain_yearly)," \
          "pre_command," \
          "post_command," \
          "description " \
          "from snapshot_schedule "
    if whereclauses:
        sql += " and ".join(whereclauses)
    sql += order_by
    db.execute(sql)
    results = db.fetchall()
    if human_output:
        print "Snapshot Schedules:"
        print "schedule_id\thostname\tinstance_id\tmount_point\tvolume_group_id\tintervals(h-d-w-m)\tretentions(h-d-w-m-y)\tpre_command\tpost_command\tdescription"
        print "---------------------------------------------------------------------------------------------------------------------------------------------------"
    for res in results:
        print "{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}".format(res[0],res[1],res[2],res[3],res[4],res[5],res[6],res[7],res[8],res[9])
    if human_output:
        print "---------------------------------------------------------------------------------------------------------------------------------------------------"


def snapshot_schedule_add(args):
    schedule = SnapshotSchedule()
    if args.resource == 'host':
        schedule.hostname = args.host
    if args.resource == 'instance':
        schedule.instance_id = args.instance_id
    if args.resource in ('host', 'instance'):
        schedule.mount_point = args.mount_point
    if args.resource == 'volume':
        schedule.volume_group_id = args.volume_group_id

    if args.intervals:
        schedule.interval_hour = args.intervals[0]
        schedule.interval_day = args.intervals[1]
        schedule.interval_week = args.intervals[2]
        schedule.interval_month = args.intervals[3]
    else:
        if args.int_hour:
            schedule.interval_hour = args.int_hour
        if args.int_day:
            schedule.interval_day = args.int_day
        if args.int_week:
            schedule.interval_week = args.int_week
        if args.int_month:
            schedule.interval_month = args.int_month
    if args.retentions:
        schedule.retain_hourly = args.retentions[0]
        schedule.retain_daily = args.retentions[1]
        schedule.retain_weekly = args.retentions[2]
        schedule.retain_monthly = args.retentions[3]
        schedule.retain_yearly = args.retentions[4]
    else:
        if args.ret_hour:
            schedule.retain_hourly = args.ret_hour
        if args.ret_day:
            schedule.retain_daily = args.ret_day
        if args.ret_week:
            schedule.retain_weekly = args.ret_week
        if args.ret_month:
            schedule.retain_monthly = args.ret_month
        if args.ret_year:
            schedule.retain_yearly = args.ret_year

    sm.schedule_snapshot(schedule)

def snapshot_schedule_edit(args):

    print "snapshot schedule edit function"

def snapshot_schedule_run(args):
    sm.run_snapshot_schedule(args.schedule_id)

def main():
    global human_output
    parser = argparse.ArgumentParser(prog="ams")
    parser.add_argument("-q", "--scriptable-output", action='store_true', help="removes human readability formatting for scripting purposes")
    #parser.add_argument("type", help="resource type to manage")
    #parser.add_argument("action", help="action to take on resource")
    subparsers = parser.add_subparsers(title="type", dest='type')


    hparser = subparsers.add_parser("host", help="direct host/instance related operations")
    hsubparser = hparser.add_subparsers(title="action", dest='action')
    hlistparser = hsubparser.add_parser("list")
    hlistparser.add_argument('search_field', nargs="?", help="field to search", choices=['host', 'instance_id'])
    hlistparser.add_argument("--like", help="string to find within 'search-field'")
    hlistparser.add_argument("--prefix", help="string to prefix match against 'search-field'")
    hlistparser.add_argument("--zone", help="Availability zone to filter results by. This is a prefix search so any of the following is valid with increasing specificity: 'us', 'us-west', 'us-west-2', 'us-west-2a'")
    hlistparser.set_defaults(func=host_list)



    vparser = subparsers.add_parser("volume", help="EBS volume and software raid operations")
    vsubparser = vparser.add_subparsers(title="action", dest='action')

    vlistparser = vsubparser.add_parser("list")
    vlistparser.add_argument('search_field', nargs="?", help="field to search", choices=['host', 'instance_id'])
    vlistparser.add_argument("--like", help="search string to use when listing resources")
    vlistparser.add_argument("--prefix", help="search string prefix to use when listing resources")
    vlistparser.add_argument("--zone", help="Availability zone to filter results by. This is a prefix search so any of the following is valid with increasing specificity: 'us', 'us-west', 'us-west-2', 'us-west-2a'")
    vlistparser.set_defaults(func=volume_list)

    vcreateparser = vsubparser.add_parser("create", help="Create new volume group.")
    vcreategroup = vcreateparser.add_mutually_exclusive_group(required=True)
    vcreategroup.add_argument('-i', '--instance', help="instance_id of an instance to attach new volume group")
    vcreategroup.add_argument('-H', '--host', help="hostname of an instance to attach new volume group")
    vcreateparser.add_argument('-n', '--numvols', type=int, help="Number of EBS volumes to create for the new volume group", required=True)
    vcreateparser.add_argument('-r', '--raid-level', type=int, help="Set the raid level for new EBS raid", default=0, choices=[0,1,5,10])
    vcreateparser.add_argument('-b', '--stripe-block-size', type=int, help="Set the stripe block/chunk size for new EBS raid", default=256)
    vcreateparser.add_argument('-m', '--mount-point', help="Set the mount point for volume. Not required, but suggested")
    vcreateparser.add_argument('-a', '--no-automount', help="Configure the OS to automatically mount the volume group on reboot", action='store_true')
    #TODO should filesystem be a limited list?
    vcreateparser.add_argument('-f', '--filesystem', help="Filesystem to partition new raid/volume", default="xfs")
    vcreateparser.add_argument('-s', '--size', type=int, help="Per EBS volume size in GiBs", required=True)
    vcreateparser.add_argument('-p', '--iops', type=int, help="Per EBS volume provisioned iops")
    vcreateparser.set_defaults(func=volume_create)

    vcreateparser = vsubparser.add_parser("attach", help="Attach, assemble (if necessary) and mount(optional) a volume group")
    vcreategroup = vcreateparser.add_mutually_exclusive_group(required=True)
    vcreateparser.add_argument('volume_group_id', type=int, help="ID of the volume group to attach to instance")
    vcreategroup.add_argument('-i', '--instance', help="instance_id of an instance to attach new volume group")
    vcreategroup.add_argument('-H', '--host', help="hostname of an instance to attach new volume group")
    vcreateparser.add_argument('-m', '--mount-point', help="Set the mount point for volume. Not required, but suggested")
    vcreateparser.add_argument('-a', '--no-automount', help="Configure the OS to automatically mount the volume group on reboot", action='store_true')
    vcreateparser.set_defaults(func=volume_attach)


    sparser = subparsers.add_parser("snapshot", help="EBS snapshot management operations")
    ssubparser = sparser.add_subparsers(title="action", dest='action')

    screateparser = ssubparser.add_parser("create", help="Create a snapshot group of a volume group")
    screatesubparser = screateparser.add_subparsers(title="resource", dest='resource')
    screatevolparser = screatesubparser.add_parser("volume", help="create a snapshot of a given volume_group_id")
    screatevolparser.add_argument('volume_group_id', type=int, help="ID of the volume group to snapshot")
    screatevolparser.add_argument("--pre", help="command to run on host to prepare for starting EBS snapshot (will not be run if volume group is not attached)")
    screatevolparser.add_argument("--post", help="command to run on host after snapshot (will not be run if volume group is not attached)")
    screatevolparser.add_argument("-d", "--description", help="description to add to snapshot(s)")
    screatevolparser.set_defaults(func=snapshot_create_volume)
    screatehostparser = screatesubparser.add_parser("host", help="create a snapshot of a specific volume group on a host")
    group = screatehostparser.add_mutually_exclusive_group(required=True)
    group.add_argument('-i', '--instance', help="instance_id of an instance to snapshot a volume group")
    group.add_argument('-H', '--host', help="hostname of an instance to snapshot a volume group")
    group = screatehostparser.add_mutually_exclusive_group(required=True)
    group.add_argument('-m', '--mount-point', help="mount point of the volume group to snapshot")
    screatehostparser.add_argument("--pre", help="command to run on host to prepare for starting EBS snapshot (will not be run if volume group is not attached)")
    screatehostparser.add_argument("--post", help="command to run on host after snapshot (will not be run if volume group is not attached)")
    screatehostparser.add_argument("-d", "--description", help="description to add to snapshot(s)")
    screatehostparser.set_defaults(func=snapshot_create_host)

    sscheduleparser = ssubparser.add_parser("schedule", help="View, add or edit snapshot schedules")
    sschedulesubparser = sscheduleparser.add_subparsers(title="subaction", dest='subaction')

    sschedulelistparser = sschedulesubparser.add_parser("list", help="List snapshot schedules")
    sschedulelistparser.add_argument('resource', help="host, instance, or volume", choices=['host', 'volume', 'instance'])
    sschedulelistparser.add_argument('resource_id', nargs='?', help="hostname, instance_id or volume_group_id")
    sschedulelistparser.add_argument("--like", help="search string to use when listing resources")
    sschedulelistparser.add_argument("--prefix", help="search string prefix to use when listing resources")
    sschedulelistparser.set_defaults(func=snapshot_schedule_list)


    scheduleaddshared = argparse.ArgumentParser(add_help=False)
    scheduleaddshared.add_argument('-i', '--intervals', type=int, nargs=4, help='Set all intervals at once', metavar=('HOUR', 'DAY', 'WEEK', 'MONTH'))
    scheduleaddshared.add_argument('-r', '--retentions', type=int, nargs=5, help='Set all retentions at once', metavar=('HOURS', 'DAYS', 'WEEKS', 'MONTHS', 'YEARS'))
    scheduleaddshared.add_argument('--int_hour', type=int, help="hourly interval for snapshots", metavar="HOURS")
    scheduleaddshared.add_argument('--int_day', type=int, help="daily interval for snapshots", metavar="DAYS")
    scheduleaddshared.add_argument('--int_week', type=int, help="weekly interval for snapshots", metavar="WEEKS")
    scheduleaddshared.add_argument('--int_month', type=int, help="monthly interval for snapshots", metavar="MONTHS")
    scheduleaddshared.add_argument('--ret_hour', type=int, help="number of hourly snapshots to keep", metavar="HOURS")
    scheduleaddshared.add_argument('--ret_day', type=int, help="number of daily snapshots to keep", metavar="DAYS")
    scheduleaddshared.add_argument('--ret_week', type=int, help="number of weekly snapshots to keep", metavar="WEEKS")
    scheduleaddshared.add_argument('--ret_month', type=int, help="number of monthly snapshots to keep", metavar="MONTHS")
    scheduleaddshared.add_argument('--ret_year', type=int, help="number of yearly snapshots to keep", metavar="YEARS")
    scheduleaddshared.add_argument("--pre", help="command to run on host to prepare for starting EBS snapshot (will not be run if volume group is not attached)")
    scheduleaddshared.add_argument("--post", help="command to run on host after snapshot (will not be run if volume group is not attached)")
    scheduleaddshared.add_argument('-d', "--description", help="description to add to snapshot")

    sscheduleaddparser = sschedulesubparser.add_parser("add", help="Create a new snapshot schedule")
    sscheduleaddparser.set_defaults(func=snapshot_schedule_add)
    sscheduleaddsubparser = sscheduleaddparser.add_subparsers(title="resource", dest="resource")
    sscheduleaddhostparser = sscheduleaddsubparser.add_parser("host", help="add a snapshot to the schedule for a specific hostname (recommended)", parents=[scheduleaddshared])
    sscheduleaddhostparser.add_argument("hostname", help="hostname to schedule snapshots for")
    group = sscheduleaddhostparser.add_mutually_exclusive_group(required=True)
    group.add_argument('-m', '--mount-point', help="mount point of the volume group to snapshot")
    sscheduleaddinstparser = sscheduleaddsubparser.add_parser("instance", help="add a snapshot to the schedule for a specific instance_id", parents=[scheduleaddshared])
    sscheduleaddinstparser.add_argument("instance_id", help="instance_id to schedule snapshots for")
    group = sscheduleaddinstparser.add_mutually_exclusive_group(required=True)
    group.add_argument('-m', '--mount-point', help="mount point of the volume group to snapshot")
    sscheduleaddinstparser = sscheduleaddsubparser.add_parser("volume", help="add a snapshot to the schedule for a specific volume_group_id", parents=[scheduleaddshared])
    sscheduleaddinstparser.add_argument("volume_group_id", help="volume_group_id to schedule snapshots for")

    sscheduleeditparser = sschedulesubparser.add_parser("edit", help="Edit a snapshot schedule", parents=[scheduleaddshared])
    sscheduleeditparser.add_argument('schedule_id', type=int, help="Snapshot schedule_id to edit (use 'ams snapshot schedule list' to list available schedules)")
    sscheduleeditparser.set_defaults(func=snapshot_schedule_edit)

    sschedulerunparser = sschedulesubparser.add_parser("run", help="Run the scheduled snapshots now")
    sschedulerunparser.add_argument('schedule_id', nargs='?', type=int, help="Snapshot schedule_id to run. If not supplied, then whatever is scheduled for the current time will run")
    sschedulerunparser.set_defaults(func=snapshot_schedule_run)

    

    args = parser.parse_args()

    print args
    if args.scriptable_output:
        human_output = False
    #dispatch(args)
    args.func(args)


if __name__ == "__main__":
    main()


